export const GIPHYS_HAS_ERRORED = 'GIPHYS_HAS_ERRORED',
  GIPHYS_ARE_LOADING = 'GIPHYS_ARE_LOADING',
  GIPHYS_GET_SUCCESS = 'GIPHYS_GET_SUCCESS';

export const GIPHY_HAS_ERRORED = 'GIPHY_HAS_ERRORED',
  GIPHY_IS_LOADING = 'GIPHY_IS_LOADING',
  GIPHY_SEARCH_SUCCESS = 'GIPHY_SEARCH_SUCCESS';
  