export const GIPHYS_HAS_ERRORED = 'GIPHYS_HAS_ERRORED',
  GIPHYS_ARE_LOADING = 'GIPHYS_ARE_LOADING',
  GIPHYS_GET_SUCCESS = 'GIPHYS_GET_SUCCESS';

export const GIPHYSEARCH_HAS_ERRORED = 'GIPHYSEARCH_HAS_ERRORED',
  GIPHYSEARCH_IS_LOADING = 'GIPHYSEARCH_IS_LOADING',
  GIPHYSEARCH_SEARCH_SUCCESS = 'GIPHYSEARCH_SEARCH_SUCCESS';
